### ISSUE TITLE
Encoding issue when chaining replies

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#7] opened 2023-05-01 05:35 UTC
Hello again!

Thank you so much for the fixes! I found another one.

There appears to be an encoding issue when chaining replies.

```
#+BEGIN_SRC assistant
Give me 5 emojis.
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
🤔😂🙌🌞😍
#+END_EXAMPLE

#+BEGIN_SRC assistant
Give me 5 more
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
\360\237\240\272\360\237\224\260\360\237\230\157\360\237\230\146\360\237\215\211
#+END_EXAMPLE
```

**Comment by walseb** [comment] 2023-05-01 05:40
It appears to be related to sending emojis in general, actually:
```
#+BEGIN_SRC assistant
Repeat the following string: 'ABC 🤔😂🙌🌞😍'
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
'ABC \360\237\244\224\360\237\230\202\360\237\231\214\360\237\214\236\360\237\230\215' 'ABC \360\237\244\224\360\237\230\202\360\237\231\214\360\237\214\236\360\237\230\215'
#+END_EXAMPLE
```

**Comment by tyler-dodge** [comment] 2023-05-01 07:54
Ended up having to sidestep this issue by switching to using curl / subprocesses instead network streams since apparently network streams do not support multi-byte encodings.

Now, this should no longer be an issue so closing.

**Closed by tyler-dodge** 2023-05-01 07:54 UTC

**Comment by walseb** [comment] 2023-05-01 12:35
Thank you!

I can confirm that it works properly now.

**Comment by tyler-dodge** [comment] 2023-05-01 17:19
> Ended up having to sidestep this issue by switching to using curl / subprocesses instead network streams since apparently network streams do not support multi-byte encodings.
> 
> Now, this should no longer be an issue so closing.

I was incorrect above about the root cause, since it does seem to be possible in other packages. I'm going to keep with the current strategy though to avoid having to deal with encoding issues further though.
