### ISSUE TITLE
Noweb bug

### ISSUE THREAD

**Issue by walseb** [tyler-dodge/org-assistant#22] opened 2023-05-06 10:44 UTC
Hello!

There is some strange noweb bug occurring when I use multiple lines in the noweb snippet and put the noweb snippet marker on a non-blank line.

It might only be present in the latest streaming branch. That's the only commit I have tried this on.

Examples:

No issue when the snippet marker is on its own line:
```
#+NAME: Test
#+BEGIN_SRC text
1
+ 1
#+END_SRC

#+BEGIN_SRC assistant :echo
What's
<<Test>>
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
(user . "What's
1
+ 1")
#+END_EXAMPLE
```

Bug occurs when it's moved to a non-empty line:
```
#+NAME: Test
#+BEGIN_SRC text
1
+ 1
#+END_SRC

#+BEGIN_SRC assistant :echo
What's <<Test>>
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
(user . "What's 1
What's + 1")
#+END_EXAMPLE
```

**Comment by walseb** [comment] 2023-05-06 10:46
After some more experiments, it appears that any characters that occur between BOL and the noweb snippet reference gets copied over to every line of the expanded noweb snippet.

**Comment by walseb** [comment] 2023-05-06 11:30
Here's a simpler example:
```
#+NAME: Foo
#+BEGIN_SRC text
foo
foo
foo
#+END_SRC

#+BEGIN_SRC assistant :echo
bar <<foo>>
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
(user . "bar foo
bar foo
bar foo")
#+END_EXAMPLE
```


```
#+NAME: Foo
#+BEGIN_SRC text
foo
foo
foo
#+END_SRC

#+BEGIN_SRC assistant :echo
bar
<<foo>>
#+END_SRC

#+RESULTS:
#+BEGIN_EXAMPLE
(user . "bar
foo
foo
foo")
#+END_EXAMPLE
```

**Comment by tyler-dodge** [comment] 2023-05-09 04:37
This is by design for org babel noweb apparently.

From org-babel-expand-noweb-references's documentation:

```
Note that any text preceding the <<foo>> construct on a line will
be interposed between the lines of the replacement text.  So for
example if <<foo>> is placed behind a comment, then the entire
replacement text will also be commented.
```
It is also referenced in the SQL example here https://orgmode.org/manual/Noweb-Reference-Syntax.html
Not what I would've expected tbh, but closing out since it's out of scope.

**Closed by tyler-dodge** 2023-05-09 04:37 UTC

**Comment by walseb** [comment] 2023-05-10 04:18
I see, that's surprising. 

Thank you for the thorough research!

**Comment by walseb** [comment] 2023-05-10 04:22
It turns out you can disable the prefixing behavior with `:noweb-prefix no`.

It appears very useful for indentation, I wonder if there is a way to have it smartly enable the prefix for indentation only.
